M48
; DRILL file KiCad 10.0.2 date 2026-05-14T09:20:38
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-14T09:20:38+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.302
%
G90
G05
T1
X146.635Y-91.612
X151.135Y-91.612
T2
X140.258Y-94.956
X157.276Y-94.956
T3
X136.363Y-114.192
X161.408Y-114.192
M30
